<?php
// Do not edit this file. Generated by admin script.
// RealEstateManager Configuration file
// General Informations 
$realestatemanager_configuration['release']['version']='3.3.1 FREE';
$realestatemanager_configuration['release']['date']='06 August 2014';
// edit house 
$realestatemanager_configuration['edithouse']['default']['lang']='';
// price settings
$realestatemanager_configuration['price']['show']='0';
$realestatemanager_configuration['price']['registrationlevel']='-2';
// auto increment for houseid, if 1 - can't add random houseid 
$realestatemanager_configuration['houseid']['auto-increment']['boolean']='0';
// review settings
$realestatemanager_configuration['reviews']['show']='1';
$realestatemanager_configuration['reviews']['registrationlevel']='7';
// show contacts
$realestatemanager_configuration['contacts']['show']='0';
$realestatemanager_configuration['contacts']['registrationlevel']='';
// show cb_myhouse
$realestatemanager_configuration['cb_myhouse']['show']='0';
$realestatemanager_configuration['cb_myhouse']['registrationlevel']='';
// show cb_edit
$realestatemanager_configuration['cb_edit']['show']='0';
$realestatemanager_configuration['cb_edit']['registrationlevel']='';
// show cb_rent
$realestatemanager_configuration['cb_rent']['show']='0';
$realestatemanager_configuration['cb_rent']['registrationlevel']='';
// show cb_buy
$realestatemanager_configuration['cb_buy']['show']='0';
$realestatemanager_configuration['cb_buy']['registrationlevel']='';
// show cb_history
$realestatemanager_configuration['cb_history']['show']='0';
$realestatemanager_configuration['cb_history']['registrationlevel']='';
// show Location
$realestatemanager_configuration['location_tab']['show']='0';
$realestatemanager_configuration ['location_tab']['registrationlevel']='';
$realestatemanager_configuration['reviews_tab']['show']='1';
$realestatemanager_configuration['reviews_tab']['registrationlevel']='-2';
// rent settings
$realestatemanager_configuration['rentstatus']['show']='1';
$realestatemanager_configuration['rentrequest']['registrationlevel']='7';
// buy settings
$realestatemanager_configuration['buystatus']['show']='1';
$realestatemanager_configuration['buyrequest']['registrationlevel']='7';
// edoc settings
$realestatemanager_configuration['edocs']['allow']='1';
$realestatemanager_configuration['edocs']['show']='1';
$realestatemanager_configuration['edocs']['registrationlevel']='-2';
$realestatemanager_configuration['edocs']['location']='/components/com_realestatemanager/edocs/';
// debuging
$realestatemanager_configuration['debug']='';
$realestatemanager_configuration['page']['items']='12';
// foto size
$realestatemanager_configuration['foto']['high']= '70';
$realestatemanager_configuration['foto']['width']= '70';
$realestatemanager_configuration['fotomain']['high']= '200';
$realestatemanager_configuration['fotomain']['width']= '350';
$realestatemanager_configuration['fotogallery']['high']= '90';
$realestatemanager_configuration['fotogallery']['width']= '90';
$realestatemanager_configuration['fotogal']['high']= '90';
$realestatemanager_configuration['fotogal']['width']= '90';
$realestatemanager_configuration['fotoupload']['high']= '600';
$realestatemanager_configuration['fotoupload']['width']= '800';
$realestatemanager_configuration['license']['show']='';
$realestatemanager_configuration['license']['text']= '<p>Untitled document</p>
<p>License Text</p>';
//user manager
$realestatemanager_configuration['user_manager_vm']['-2']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['-2']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['29']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['29']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['18']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['18']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['19']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['19']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['20']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['20']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['21']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['21']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['32']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['32']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['30']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['30']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['23']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['23']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['24']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['24']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['25']['count_car']='5';
$realestatemanager_configuration['user_manager_vm']['25']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['1']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['1']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['6']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['6']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['7']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['7']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['2']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['2']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['3']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['3']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['4']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['4']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['5']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['5']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['8']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['8']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['10']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['10']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['12']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['12']['count_foto']='';
$realestatemanager_configuration['user_manager_vm']['9']['count_car']='0';
$realestatemanager_configuration['user_manager_vm']['9']['count_foto']='0';
$realestatemanager_configuration['user_manager_vm']['11']['count_car']='11';
$realestatemanager_configuration['user_manager_vm']['11']['count_foto']='';
// paypal rent settings
$realestatemanager_configuration['paypal_rent_status']['show']='0';
$realestatemanager_configuration['paypal_rent']['registrationlevel']='';
$realestatemanager_configuration['pay_pal_rent']['business']='';
$realestatemanager_configuration['pay_pal_rent']['return']='';
$realestatemanager_configuration['pay_pal_rent']['image_url']='';
$realestatemanager_configuration['pay_pal_rent']['cancel_return']='';
$realestatemanager_configuration['paypal_real_or_test']['show']='0';
// paypal buy settings
$realestatemanager_configuration['special_price']['show']='0';
$realestatemanager_configuration['paypal_buy_status']['show']='0';
$realestatemanager_configuration['paypal_buy']['registrationlevel']='';
$realestatemanager_configuration['pay_pal_buy']['business']='';
$realestatemanager_configuration['pay_pal_buy']['return']='';
$realestatemanager_configuration['pay_pal_buy']['image_url']='';
$realestatemanager_configuration['pay_pal_buy']['cancel_return']='';
// button '[ Suggest a house ]'
$realestatemanager_configuration['add_suggest']['show']='0';
$realestatemanager_configuration['add_suggest']['registrationlevel']='';
// button '[ Add a house ]'
$realestatemanager_configuration['add_house']['show']='0';
$realestatemanager_configuration['add_house']['registrationlevel']='';
// button '[ print PDF ]'
$realestatemanager_configuration['print_pdf']['show']='0';
$realestatemanager_configuration['print_pdf']['registrationlevel']='';
// button '[ print View ]'
$realestatemanager_configuration['print_view']['show']='0';
$realestatemanager_configuration['print_view']['registrationlevel']='';
// button '[ mail_to ]'
$realestatemanager_configuration['mail_to']['show']='0';
$realestatemanager_configuration['mail_to']['registrationlevel']='';
// send email for admin
$realestatemanager_configuration['add_email']['address']='';
$realestatemanager_configuration['add_email']['show']='0';
$realestatemanager_configuration['add_email']['registrationlevel']='';
$realestatemanager_configuration['review_email']['address']='';
$realestatemanager_configuration['review_added_email']['show']='0';
$realestatemanager_configuration['review_added_email']['registrationlevel']='';
$realestatemanager_configuration['suggest_email']['address']='';
$realestatemanager_configuration['suggest_added_email']['show']='0';
$realestatemanager_configuration['suggest_added_email']['registrationlevel']='';
$realestatemanager_configuration['rentrequest_email']['address']='';
$realestatemanager_configuration['rentrequest_email']['show']='1';
$realestatemanager_configuration['rentrequest_email']['registrationlevel']='';
$realestatemanager_configuration['buyingrequest_email']['address']='';
$realestatemanager_configuration['buyingrequest_email']['show']='0';
$realestatemanager_configuration['buyingrequest_email']['registrationlevel']='';
// show in category picture
$realestatemanager_configuration['cat_pic']['show']='1';
$realestatemanager_configuration['approve_review']['show']='';
$realestatemanager_configuration['approve_review']['registrationlevel']='';
// show subcategory
$realestatemanager_configuration['subcategory']['show']='1';
$realestatemanager_configuration['owner']['show']='';
$realestatemanager_configuration['approve_on_add']['show']='';
$realestatemanager_configuration['approve_on_add']['registrationlevel']='';
$realestatemanager_configuration['publish_on_add']['show']='';
$realestatemanager_configuration['publish_on_add']['registrationlevel']='';
$realestatemanager_configuration['publish_on_review']['show']='';
$realestatemanager_configuration['publish_on_review']['registrationlevel']='';
//view type
$realestatemanager_configuration['view_type']='default';
//all_categories
$realestatemanager_configuration['all_categories']='default';
//view_house
$realestatemanager_configuration['view_house']='default';
//show location map
$realestatemanager_configuration['location_map']='1';
//show_search_house
$realestatemanager_configuration['show_search_house']='default';
//layout_all_houses
$realestatemanager_configuration['layout_all_houses']='';
//update
$realestatemanager_configuration['update']='0';
$realestatemanager_configuration['rss']['show']='';
$realestatemanager_configuration['rss']['registrationlevel']='';
$realestatemanager_configuration['owner']['show']='';
$realestatemanager_configuration['ownerslist']['show']='';
$realestatemanager_configuration['ownerslist']['registrationlevel']='';
$realestatemanager_configuration['calendar']['show']='1';
$realestatemanager_configuration['calendarlist']['show']='';
$realestatemanager_configuration['calendarlist']['registrationlevel']='-2';
$realestatemanager_configuration['rent_answer']='0';
$realestatemanager_configuration['rent_form']='0';
$realestatemanager_configuration['buy_answer']='0';
$realestatemanager_configuration['buy_form']='0';
//end rent notify
$realestatemanager_configuration['rent_before_end_notify']='0';
$realestatemanager_configuration['rent_before_end_notify_days']='2';
$realestatemanager_configuration['rent_before_end_notify_email']='';
$realestatemanager_configuration['calendar']['placeholder']='';
//manager_feature_image
$realestatemanager_configuration['manager_feature_image']='1';
//manager_feature_category
$realestatemanager_configuration['manager_feature_category']='1';
//sale_separator
$realestatemanager_configuration['sale_separator']='0';
//extra1
$realestatemanager_configuration['extra1']='1';
//extra2
$realestatemanager_configuration['extra2']='1';
//extra3
$realestatemanager_configuration['extra3']='1';
//extra4
$realestatemanager_configuration['extra4']='0';
//extra5
$realestatemanager_configuration['extra5']='0';
//extra6
$realestatemanager_configuration['extra6']='0';
//extra7
$realestatemanager_configuration['extra7']='0';
//extra8
$realestatemanager_configuration['extra8']='0';
//extra9
$realestatemanager_configuration['extra9']='0';
//extra10
$realestatemanager_configuration['extra10']='0';
$realestatemanager_configuration['featuredmanager']['placeholder']='Activities, Distances, Outside, Inside';
$realestatemanager_configuration['currency']='USD=1;EUR=8.125;RUB=240;';
$realestatemanager_configuration['allowed_exts']='zip,pdf';
$realestatemanager_configuration['allowed_exts_img']='jpeg,jpg,png,gif';
$realestatemanager_configuration['price_format']=' ';
// 1 - affter 0 - beffore
$realestatemanager_configuration['price_unit_show']='1';
$realestatemanager_configuration['date_format']='%Y-%m-%d';
$realestatemanager_configuration['datetime_format']='%H:%i:%s';
?>