<?php

if (!defined('_VALID_MOS') && !defined('_JEXEC'))
    die('Direct Access to ' . basename(__FILE__) . ' is not allowed.');

/**
 *
 * @package  RealEstateManager
 * @copyright 2012 Andrey Kvasnevskiy-OrdaSoft(akbet@mail.ru); Rob de Cleen(rob@decleen.com); 
 * Homepage: http://www.ordasoft.com
 * @version: 3.0 Pro
 *
 * */
class mosRealEstateManagerOthers {

    /**
     * Sets the parametes for connecting to a webservice via a 
     * @param the array of parameters
     * @deprecated $Revision: 1.0 $ - December 2007
     */
    static function setParams() {
        global $realestatemanager_configuration;
        // Prepare settings
        // Using single quotes is easier because you don't have to escape them. For every setting, add a line.
        $settings = "<?php\n";
        $settings .= "// Do not edit this file. Generated by admin script.\n";
        $settings .= "// RealEstateManager Configuration file\n";
        $settings .= "// General Informations \n";
        $settings .= "\$realestatemanager_configuration['release']['version']='" . $realestatemanager_configuration['release']['version'] . "';\n";
        $settings .= "\$realestatemanager_configuration['release']['date']='" . $realestatemanager_configuration['release']['date'] . "';\n";
        $settings .= "// edit house \n";
        $settings .= "\$realestatemanager_configuration['edithouse']['default']['lang']='" . $realestatemanager_configuration['edithouse']['default']['lang'] . "';\n";
        $settings .= "// price settings\n";
        $settings .= "\$realestatemanager_configuration['price']['show']='" . $realestatemanager_configuration['price']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['price']['registrationlevel']='" . $realestatemanager_configuration['price']['registrationlevel'] . "';\n";
        $settings .= "// auto increment for houseid, if 1 - can't add random houseid \n";
        $settings .= "\$realestatemanager_configuration['houseid']['auto-increment']['boolean']='" . $realestatemanager_configuration['houseid']['auto-increment']['boolean'] . "';\n";
        $settings .= "// review settings\n";
        $settings .= "\$realestatemanager_configuration['reviews']['show']='" . $realestatemanager_configuration['reviews']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['reviews']['registrationlevel']='" . $realestatemanager_configuration['reviews']['registrationlevel'] . "';\n";
        $settings .= "// show contacts\n";
        $settings .= "\$realestatemanager_configuration['contacts']['show']='" .
                $realestatemanager_configuration['contacts']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['contacts']['registrationlevel']='" .
                $realestatemanager_configuration['contacts']['registrationlevel'] . "';\n";

// --------------------------community builder section------------------------
        $settings .= "// show cb_myhouse\n";
        $settings .= "\$realestatemanager_configuration['cb_myhouse']['show']='" . $realestatemanager_configuration['cb_myhouse']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['cb_myhouse']['registrationlevel']='" . $realestatemanager_configuration['cb_myhouse']['registrationlevel'] . "';\n";
        $settings .= "// show cb_edit\n";
        $settings .= "\$realestatemanager_configuration['cb_edit']['show']='" . $realestatemanager_configuration['cb_edit']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['cb_edit']['registrationlevel']='" . $realestatemanager_configuration['cb_edit']['registrationlevel'] . "';\n";
        $settings .= "// show cb_rent\n";
        $settings .= "\$realestatemanager_configuration['cb_rent']['show']='" . $realestatemanager_configuration['cb_rent']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['cb_rent']['registrationlevel']='" . $realestatemanager_configuration['cb_rent']['registrationlevel'] . "';\n";
        $settings .= "// show cb_buy\n";
        $settings .= "\$realestatemanager_configuration['cb_buy']['show']='" . $realestatemanager_configuration['cb_buy']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['cb_buy']['registrationlevel']='" . $realestatemanager_configuration['cb_buy']['registrationlevel'] . "';\n";
        $settings .= "// show cb_history\n";
        $settings .= "\$realestatemanager_configuration['cb_history']['show']='" . $realestatemanager_configuration['cb_history']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['cb_history']['registrationlevel']='" . $realestatemanager_configuration['cb_history']['registrationlevel'] . "';\n";
// --------------------------end community builder section---------------------    

        $settings .= "// show Location\n";
        $settings .= "\$realestatemanager_configuration['location_tab']['show']='" . $realestatemanager_configuration['location_tab']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration ['location_tab']['registrationlevel']='" . $realestatemanager_configuration ['location_tab']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['reviews_tab']['show']='" . $realestatemanager_configuration['reviews_tab']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['reviews_tab']['registrationlevel']='" . $realestatemanager_configuration['reviews_tab']['registrationlevel'] . "';\n";
        $settings .= "// rent settings\n";
        $settings .= "\$realestatemanager_configuration['rentstatus']['show']='" . $realestatemanager_configuration['rentstatus']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rentrequest']['registrationlevel']='" . $realestatemanager_configuration['rentrequest']['registrationlevel'] . "';\n";
        $settings .= "// buy settings\n";
        $settings .= "\$realestatemanager_configuration['buystatus']['show']='" . $realestatemanager_configuration['buystatus']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['buyrequest']['registrationlevel']='" . $realestatemanager_configuration['buyrequest']['registrationlevel'] . "';\n";
        $settings .= "// edoc settings\n";
        $settings .= "\$realestatemanager_configuration['edocs']['allow']='" . $realestatemanager_configuration['edocs']['allow'] . "';\n";
        $settings .= "\$realestatemanager_configuration['edocs']['show']='" . $realestatemanager_configuration['edocs']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['edocs']['registrationlevel']='" . $realestatemanager_configuration['edocs']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['edocs']['location']='" . $realestatemanager_configuration['edocs']['location'] . "';\n";
        $settings .= "// debuging\n";
        $settings .= "\$realestatemanager_configuration['debug']='" . $realestatemanager_configuration['debug'] . "';\n";
        $settings .= "\$realestatemanager_configuration['page']['items']='" . $realestatemanager_configuration['page']['items'] . "';\n";
        $settings .= "// foto size\n";
        $settings .= "\$realestatemanager_configuration['foto']['high']= '" . $realestatemanager_configuration['foto']['high'] . "';\n";
        $settings .= "\$realestatemanager_configuration['foto']['width']= '" . $realestatemanager_configuration['foto']['width'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotomain']['high']= '" . $realestatemanager_configuration['fotomain']['high'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotomain']['width']= '" . $realestatemanager_configuration['fotomain']['width'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotogallery']['high']= '" . $realestatemanager_configuration['fotogallery']['high'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotogallery']['width']= '" . $realestatemanager_configuration['fotogallery']['width'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotogal']['high']= '" . $realestatemanager_configuration['fotogallery']['high'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotogal']['width']= '" . $realestatemanager_configuration['fotogallery']['width'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotoupload']['high']= '" . $realestatemanager_configuration['fotoupload']['high'] . "';\n";
        $settings .= "\$realestatemanager_configuration['fotoupload']['width']= '" . $realestatemanager_configuration['fotoupload']['width'] . "';\n";
        $settings .= "\$realestatemanager_configuration['license']['show']='" . $realestatemanager_configuration['license']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['license']['text']= '" . $realestatemanager_configuration['license']['text'] . "';\n";
        //user manager
        $settings .= "//user manager\n";        
        $keys = array_keys( $realestatemanager_configuration['user_manager_vm'] );
        // iterate through styles
        foreach( $keys as $key ){
            $settings .= "\$realestatemanager_configuration['user_manager_vm']['$key']['count_car']='" . $realestatemanager_configuration
            ['user_manager_vm'][$key]['count_car'] ."';\n";
            $settings .= "\$realestatemanager_configuration['user_manager_vm']['$key']['count_foto']='" . $realestatemanager_configuration
            ['user_manager_vm'][$key]['count_foto'] ."';\n";
        }
        //PayPal
        $settings .= "// paypal rent settings\n";
        $settings .= "\$realestatemanager_configuration['paypal_rent_status']['show']='" .
                $realestatemanager_configuration['paypal_rent_status']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['paypal_rent']['registrationlevel']='" .
                $realestatemanager_configuration['paypal_rent']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_rent']['business']='" . $realestatemanager_configuration['pay_pal_rent']['business'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_rent']['return']='" . $realestatemanager_configuration['pay_pal_rent']['return'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_rent']['image_url']='" . $realestatemanager_configuration['pay_pal_rent']['image_url'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_rent']['cancel_return']='" . $realestatemanager_configuration['pay_pal_rent']['cancel_return'] . "';\n";
        $settings .= "\$realestatemanager_configuration['paypal_real_or_test']['show']='" . $realestatemanager_configuration['paypal_real_or_test']['show'] . "';\n";
                
        $settings .= "// paypal buy settings\n";
        $settings .= "\$realestatemanager_configuration['special_price']['show']='" . $realestatemanager_configuration['special_price']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['paypal_buy_status']['show']='" .
                $realestatemanager_configuration['paypal_buy_status']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['paypal_buy']['registrationlevel']='" .
                $realestatemanager_configuration['paypal_buy']['registrationlevel'] . "';\n";
               
        $settings .= "\$realestatemanager_configuration['pay_pal_buy']['business']='" . $realestatemanager_configuration['pay_pal_buy']['business'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_buy']['return']='" . $realestatemanager_configuration['pay_pal_buy']['return'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_buy']['image_url']='" . $realestatemanager_configuration['pay_pal_buy']['image_url'] . "';\n";
        $settings .= "\$realestatemanager_configuration['pay_pal_buy']['cancel_return']='" . $realestatemanager_configuration['pay_pal_buy']['cancel_return'] . "';\n";
        
//********   begin add for Manager Suggestion: button 'Suggest a house'   *****
        $settings .= "// button '[ Suggest a house ]'\n";
        $settings .= "\$realestatemanager_configuration['add_suggest']['show']='" . $realestatemanager_configuration['add_suggest']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['add_suggest']['registrationlevel']='" . $realestatemanager_configuration['add_suggest']['registrationlevel'] . "';\n";
//*****   end add for Manager Suggestion: button 'Suggest a house'  ***********
//************   begin add for Manager Add: button 'Add a house'   ************
        $settings .= "// button '[ Add a house ]'\n";
        $settings .= "\$realestatemanager_configuration['add_house']['show']='" . $realestatemanager_configuration['add_house']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['add_house']['registrationlevel']='" . $realestatemanager_configuration['add_house']['registrationlevel'] . "';\n";
//*****   end add for Manager  Add: button ' Add a house'  ***********    
//*******   begin add for  Manager print_pdf: button 'print PDF'    ******************************
        $settings .= "// button '[ print PDF ]'\n";
        $settings .= "\$realestatemanager_configuration['print_pdf']['show']='" . $realestatemanager_configuration['print_pdf']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['print_pdf']['registrationlevel']='" . $realestatemanager_configuration['print_pdf']['registrationlevel'] . "';\n";
//*****    end add for  Manager print_pdf: button 'print PDF'    ***********
//********   begin add for  Manager print_view: button 'print View'    ******************************
        $settings .= "// button '[ print View ]'\n";
        $settings .= "\$realestatemanager_configuration['print_view']['show']='" . $realestatemanager_configuration['print_view']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['print_view']['registrationlevel']='" . $realestatemanager_configuration['print_view']['registrationlevel'] . "';\n";
//*****    end add for  Manager print_view: button 'print View'    ***********
//****   begin add for  Manager mail_to: button 'mail_to'    ******************************
        $settings .= "// button '[ mail_to ]'\n";
        $settings .= "\$realestatemanager_configuration['mail_to']['show']='" . $realestatemanager_configuration['mail_to']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['mail_to']['registrationlevel']='" . $realestatemanager_configuration['mail_to']['registrationlevel'] . "';\n";
//*****    end add for  Manager mail_to: button 'mail_to'    ***********
//*************************   begin add send mail for admin  ************
        $settings .= "// send email for admin\n";
        $settings .= "\$realestatemanager_configuration['add_email']['address']='" . $realestatemanager_configuration['add_email']['address'] . "';\n";
        $settings .= "\$realestatemanager_configuration['add_email']['show']='" . $realestatemanager_configuration['add_email']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['add_email']['registrationlevel']='" . $realestatemanager_configuration['add_email']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['review_email']['address']='" . $realestatemanager_configuration['review_email']['address'] . "';\n";
        $settings .= "\$realestatemanager_configuration['review_added_email']['show']='" . $realestatemanager_configuration['review_added_email']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['review_added_email']['registrationlevel']='" . $realestatemanager_configuration['review_added_email']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['suggest_email']['address']='" . $realestatemanager_configuration['suggest_email']['address'] . "';\n";
        $settings .= "\$realestatemanager_configuration['suggest_added_email']['show']='" . $realestatemanager_configuration['suggest_added_email']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['suggest_added_email']['registrationlevel']='" . $realestatemanager_configuration['suggest_added_email']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rentrequest_email']['address']='" . $realestatemanager_configuration['rentrequest_email']['address'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rentrequest_email']['show']='" . $realestatemanager_configuration['rentrequest_email']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rentrequest_email']['registrationlevel']='" . $realestatemanager_configuration['rentrequest_email']['registrationlevel'] . "';\n";
        $settings .= "\$realestatemanager_configuration['buyingrequest_email']['address']='" . $realestatemanager_configuration['buyingrequest_email']['address'] . "';\n";
        $settings .= "\$realestatemanager_configuration['buyingrequest_email']['show']='" . $realestatemanager_configuration['buyingrequest_email']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['buyingrequest_email']['registrationlevel']='" . $realestatemanager_configuration['buyingrequest_email']['registrationlevel'] . "';\n";
//*************************   end add send mail for admin   *************
        //add for show in category picture
        $settings .= "// show in category picture\n";
        $settings .= "\$realestatemanager_configuration['cat_pic']['show']='" . $realestatemanager_configuration['cat_pic']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['approve_review']['show']='" . $realestatemanager_configuration['approve_review']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['approve_review']['registrationlevel']='" . $realestatemanager_configuration['approve_review']['registrationlevel'] . "';\n";
        
        //add for show subcategory
        $settings .= "// show subcategory\n";
        $settings .= "\$realestatemanager_configuration['subcategory']['show']='" . $realestatemanager_configuration['subcategory']['show'] . "';\n";

        $settings .= "\$realestatemanager_configuration['owner']['show']='" . $realestatemanager_configuration['owner']['show'] . "';\n";


//********************************** begin show approve_on_add 	****************************
        $settings .= "\$realestatemanager_configuration['approve_on_add']['show']='" . $realestatemanager_configuration['approve_on_add']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['approve_on_add']['registrationlevel']='" . $realestatemanager_configuration['approve_on_add']['registrationlevel'] . "';\n";
//********************* end show approve_on_add 	******************************************
//********************************** begin show publish_on_add 	****************************
        $settings .= "\$realestatemanager_configuration['publish_on_add']['show']='" . $realestatemanager_configuration['publish_on_add']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['publish_on_add']['registrationlevel']='" . $realestatemanager_configuration['publish_on_add']['registrationlevel'] . "';\n";
//********************* end show publish_on_add 	******************************************
//********************************** begin show publish_on_review 	****************************
        $settings .= "\$realestatemanager_configuration['publish_on_review']['show']='" . $realestatemanager_configuration['publish_on_review']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['publish_on_review']['registrationlevel']='" . $realestatemanager_configuration['publish_on_review']['registrationlevel'] . "';\n";
//********************* end show publish_on_review 	******************************************
        //view type house
        $settings .= "//view type\n";
        $settings .= "\$realestatemanager_configuration['view_type']='" . $realestatemanager_configuration['view_type'] . "';\n";

        //view type houses
        $settings .= "//all_categories\n";
        $settings .= "\$realestatemanager_configuration['all_categories']='" . $realestatemanager_configuration['all_categories'] . "';\n";

        $settings .= "//view_house\n";
        $settings .= "\$realestatemanager_configuration['view_house']='" . $realestatemanager_configuration['view_house'] . "';\n";

        //show location map
        $settings .= "//show location map\n";
        $settings .= "\$realestatemanager_configuration['location_map']='" . $realestatemanager_configuration['location_map'] . "';\n";
        //show search house
        $settings .= "//show_search_house\n";
        $settings .= "\$realestatemanager_configuration['show_search_house']='" . $realestatemanager_configuration['show_search_house'] . "';\n";
        //layout all houses
        $settings .= "//layout_all_houses\n";
        $settings .= "\$realestatemanager_configuration['layout_all_houses']='" . $realestatemanager_configuration['layout_all_houses'] . "';\n";
        //update
        $settings .= "//update\n";
        $settings .= "\$realestatemanager_configuration['update']='" . $realestatemanager_configuration['update'] . "';\n";

        // *****  RSS *********
        $settings .= "\$realestatemanager_configuration['rss']['show']='" . $realestatemanager_configuration['rss']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rss']['registrationlevel']='" . $realestatemanager_configuration['rss']['registrationlevel'] . "';\n";
        // *****  end RSS *********

        $settings .= "\$realestatemanager_configuration['owner']['show']='" . $realestatemanager_configuration['owner']['show'] . "';\n";

        // *****  Owners list *********
        $settings .= "\$realestatemanager_configuration['ownerslist']['show']='" . $realestatemanager_configuration['ownerslist']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['ownerslist']['registrationlevel']='" . $realestatemanager_configuration['ownerslist']['registrationlevel'] . "';\n";
        // *****  END Owners list *********
        $settings .= "\$realestatemanager_configuration['calendar']['show']='" . $realestatemanager_configuration['calendar']['show'] . "';\n";
        // *****  Calendar list *********
        $settings .= "\$realestatemanager_configuration['calendarlist']['show']='" . $realestatemanager_configuration['calendarlist']['show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['calendarlist']['registrationlevel']='" . $realestatemanager_configuration['calendarlist']['registrationlevel'] . "';\n";
        // *****  END Calendar list *********

        $settings .= "\$realestatemanager_configuration['rent_answer']='" . $realestatemanager_configuration['rent_answer'] . "';\n";

        //******* Rent Request form******
        $settings .= "\$realestatemanager_configuration['rent_form']='" . $realestatemanager_configuration['rent_form'] . "';\n";
        //******* Buy Request form******
        $settings .= "\$realestatemanager_configuration['buy_answer']='" . $realestatemanager_configuration['buy_answer'] . "';\n";
        $settings .= "\$realestatemanager_configuration['buy_form']='" . $realestatemanager_configuration['buy_form'] . "';\n";
        $settings .= "//end rent notify\n";
        $settings .= "\$realestatemanager_configuration['rent_before_end_notify']='" . $realestatemanager_configuration['rent_before_end_notify'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rent_before_end_notify_days']='" . $realestatemanager_configuration['rent_before_end_notify_days'] . "';\n";
        $settings .= "\$realestatemanager_configuration['rent_before_end_notify_email']='" . $realestatemanager_configuration['rent_before_end_notify_email'] . "';\n";
        $settings .= "\$realestatemanager_configuration['calendar']['placeholder']='" . $realestatemanager_configuration['calendar']['placeholder'] . "';\n";
        //show manager_feature_image
        $settings .= "//manager_feature_image\n";
        $settings .= "\$realestatemanager_configuration['manager_feature_image']='" .
                $realestatemanager_configuration['manager_feature_image'] . "';\n";
        //manager_feature_category
        $settings .= "//manager_feature_category\n";
        $settings .= "\$realestatemanager_configuration['manager_feature_category']='" .
                $realestatemanager_configuration['manager_feature_category'] . "';\n";
        //sale_separator
        $settings .= "//sale_separator\n";
        $settings .= "\$realestatemanager_configuration['sale_separator']='" .
                $realestatemanager_configuration['sale_separator'] . "';\n";
        //show extra
        $settings .= "//extra1\n";
        $settings .= "\$realestatemanager_configuration['extra1']='" .
                $realestatemanager_configuration['extra1'] . "';\n";
        $settings .= "//extra2\n";
        $settings .= "\$realestatemanager_configuration['extra2']='" .
                $realestatemanager_configuration['extra2'] . "';\n";
        $settings .= "//extra3\n";
        $settings .= "\$realestatemanager_configuration['extra3']='" .
                $realestatemanager_configuration['extra3'] . "';\n";
        $settings .= "//extra4\n";
        $settings .= "\$realestatemanager_configuration['extra4']='" .
                $realestatemanager_configuration['extra4'] . "';\n";
        $settings .= "//extra5\n";
        $settings .= "\$realestatemanager_configuration['extra5']='" .
                $realestatemanager_configuration['extra5'] . "';\n";
        $settings .= "//extra6\n";
        $settings .= "\$realestatemanager_configuration['extra6']='" .
                $realestatemanager_configuration['extra6'] . "';\n";
        $settings .= "//extra7\n";
        $settings .= "\$realestatemanager_configuration['extra7']='" .
                $realestatemanager_configuration['extra7'] . "';\n";
        $settings .= "//extra8\n";
        $settings .= "\$realestatemanager_configuration['extra8']='" .
                $realestatemanager_configuration['extra8'] . "';\n";
        $settings .= "//extra9\n";
        $settings .= "\$realestatemanager_configuration['extra9']='" .
                $realestatemanager_configuration['extra9'] . "';\n";
        $settings .= "//extra10\n";
        $settings .= "\$realestatemanager_configuration['extra10']='" .
                $realestatemanager_configuration['extra10'] . "';\n";

        $settings .= "\$realestatemanager_configuration['featuredmanager']['placeholder']='" . $realestatemanager_configuration['featuredmanager']['placeholder'] . "';\n";
        $settings .= "\$realestatemanager_configuration['currency']='" . $realestatemanager_configuration['currency'] . "';\n";
        $settings .= "\$realestatemanager_configuration['allowed_exts']='" . $realestatemanager_configuration['allowed_exts'] . "';\n";
        $settings .= "\$realestatemanager_configuration['allowed_exts_img']='" . $realestatemanager_configuration['allowed_exts_img'] . "';\n";

        $settings .= "\$realestatemanager_configuration['price_format']='" . $realestatemanager_configuration['price_format'] . "';\n";
        $settings .= "// 1 - affter 0 - beffore\n";
        $settings .= "\$realestatemanager_configuration['price_unit_show']='" . $realestatemanager_configuration['price_unit_show'] . "';\n";
        $settings .= "\$realestatemanager_configuration['date_format']='" . $realestatemanager_configuration['date_format'] . "';\n";
        $settings .= "\$realestatemanager_configuration['datetime_format']='" . $realestatemanager_configuration['datetime_format'] . "';\n";
        $settings .= "?>";

        // Write out new initialization file
        $fd = fopen("./components/com_realestatemanager/realestatemanager.class.conf.php", "w")
                or die("Cannot create configuration file.");
        fwrite($fd, $settings);
        fclose($fd);
    }

    /**
     * Rating Array
     * @return array an Array containing the information of all Rating
     * possibilities
     */
    static function getRatingArray() {
        $i = 0;
        $retVal = array();
        while ($i < 5) {
            //erster teil x,0
            $tmp = $i * 2;
            array_push($retVal, array($tmp, $i . ",0"));
            //zweiter teil x,5
            $tmp++;
            array_push($retVal, array($tmp, $i . ",5"));
            $i++;
        }
        array_push($retVal, array(10, "10,0"));
        return $retVal;
    }

    /**
     * Language Array - defined in the language files!
     * @return array an Array containing the information of all Language
     * possibilities
     */
    static function getLanguageArray() {
        $retVal = array();
        array_push($retVal, array("Not specified", _REALESTATE_MANAGER_LANGUAGE_NOT_USED));
        array_push($retVal, array("Brazilian Portuguese", _REALESTATE_MANAGER_LANGUAGE_PTBR));
        array_push($retVal, array("Danish", _REALESTATE_MANAGER_LANGUAGE_DK));
        array_push($retVal, array("Dutch", _REALESTATE_MANAGER_LANGUAGE_DUT));
        array_push($retVal, array("English", _REALESTATE_MANAGER_LANGUAGE_ENG));
        array_push($retVal, array("Farsi", _REALESTATE_MANAGER_LANGUAGE_FAR));
        array_push($retVal, array("French", _REALESTATE_MANAGER_LANGUAGE_FRE));
        array_push($retVal, array("German", _REALESTATE_MANAGER_LANGUAGE_GER));
        array_push($retVal, array("Italian", _REALESTATE_MANAGER_LANGUAGE_ITA));
        array_push($retVal, array("Portuguese", _REALESTATE_MANAGER_LANGUAGE_PR));
        array_push($retVal, array("Romanian", _REALESTATE_MANAGER_LANGUAGE_ROM));
        array_push($retVal, array("Russian", _REALESTATE_MANAGER_LANGUAGE_RUS));
        array_push($retVal, array("Spanish", _REALESTATE_MANAGER_LANGUAGE_SPA));
        array_push($retVal, array("Swedish", _REALESTATE_MANAGER_LANGUAGE_SWE));
        return $retVal;
    }

}